"""论文评分卡生成器 - 用 matplotlib 生成五维雷达图 PNG

功能：输入论文 + 评级 → 生成可分享的评分卡 PNG（带水印）
"""

import matplotlib
matplotlib.use('Agg')  # 非交互式后端，必须在使用 pyplot 前设置
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import numpy as np
from io import BytesIO
from typing import Dict, Any


# ==================== 中文字体配置 ====================
# 跨平台兼容：Windows=Microsoft YaHei / Linux=WenQuanYi Zen Hei / macOS=PingFang SC
# 不配置的话中文会显示为方框（DejaVu Sans 不含 CJK 字符）

def _setup_chinese_font():
    """设置 matplotlib 使用支持中文的字体"""
    # 按优先级查找可用字体
    candidates = [
        'Microsoft YaHei',     # Windows
        'WenQuanYi Zen Hei',   # Linux (Docker 装了 fonts-wqy-zenhei)
        'WenQuanYi Micro Hei', # Linux 备用
        'PingFang SC',         # macOS
        'SimHei',              # Windows 备用
        'Noto Sans CJK SC',    # Linux 通用
    ]
    available_fonts = set(f.name for f in fm.fontManager.ttflist)
    for font_name in candidates:
        if font_name in available_fonts:
            plt.rcParams['font.sans-serif'] = [font_name, 'DejaVu Sans']
            plt.rcParams['axes.unicode_minus'] = False  # 负号正常显示
            return font_name
    # 全部都没找到，降级使用默认字体（中文会显示为方框）
    return None

# 模块加载时自动配置
_ACTIVE_FONT = _setup_chinese_font()


# ==================== 配置 ====================

# 评级等级对应的颜色（与前端 gradeColor 保持一致）
GRADE_COLORS = {
    'S': '#ff4444',  # 红色 - 顶级
    'A': '#ff8800',  # 橙色 - 优秀
    'B': '#ffcc00',  # 黄色 - 良好
    'C': '#88cc00',  # 绿色 - 中等
    'D': '#88aaff',  # 蓝色 - 较低
}

# 五维标签（中英对照，雷达图用中文更直观）
DIM_LABELS = ['学术影响力', '商业潜力', '创新指数', '可复现性', '组合价值']
DIM_KEYS = ['academic_impact', 'commercial_potential', 'innovation_index',
            'reproducibility', 'combo_value']


def generate_scorecard(paper: Dict[str, Any], rating: Dict[str, Any]) -> bytes:
    """生成论文评分卡 PNG 图片

    Args:
        paper: 论文字典，需要 title 字段
        rating: 评级字典，需要五维评分字段 + rating_level/grade

    Returns:
        PNG 图片的字节数据
    """
    # 获取评级等级（兼容 rating_level 和 grade 两种字段名）
    grade = rating.get('rating_level') or rating.get('grade') or 'C'
    color = GRADE_COLORS.get(grade, '#88aaff')

    # 提取五维分数（默认 0，combo_value 默认 50）
    values = []
    for i, key in enumerate(DIM_KEYS):
        v = rating.get(key)
        if v is None:
            v = 50 if key == 'combo_value' else 0
        try:
            v = float(v)
        except (TypeError, ValueError):
            v = 0
        values.append(min(100, max(0, v)))

    # 闭合雷达图（首尾相连）
    values_closed = values + values[:1]
    angles = np.linspace(0, 2 * np.pi, len(DIM_LABELS), endpoint=False).tolist()
    angles_closed = angles + angles[:1]

    # 创建极坐标图
    fig, ax = plt.subplots(figsize=(8, 9), subplot_kw=dict(polar=True))

    # 填充区域
    ax.fill(angles_closed, values_closed, alpha=0.25, color=color)
    ax.plot(angles_closed, values_closed, linewidth=2.5, color=color, marker='o',
            markersize=8, markerfacecolor=color, markeredgecolor='white', markeredgewidth=2)

    # 设置雷达图标签
    ax.set_xticks(angles)
    ax.set_xticklabels(DIM_LABELS, fontsize=11, fontweight='bold')

    # 设置径向轴范围
    ax.set_ylim(0, 100)
    ax.set_yticks([20, 40, 60, 80, 100])
    ax.set_yticklabels(['20', '40', '60', '80', '100'], fontsize=8, color='grey')
    ax.grid(True, linestyle='--', alpha=0.5)

    # 标题：评级等级 + 论文标题（截断到 60 字符避免溢出）
    title = paper.get('title') or '未命名论文'
    if len(title) > 60:
        title = title[:57] + '...'
    plt.title(f'PAE 评级：{grade} 级\n{title}',
              fontsize=13, fontweight='bold', pad=25, color='#303133')

    # 综合评分（右上角显示）
    overall = rating.get('overall_score')
    if overall is not None:
        fig.text(0.95, 0.95, f'综合评分：{overall}',
                 ha='right', va='top', fontsize=11, fontweight='bold',
                 bbox=dict(boxstyle='round,pad=0.5', facecolor=color, alpha=0.8,
                           edgecolor='none'), color='white')

    # 论文元信息（左下角）
    meta_lines = []
    if paper.get('year'):
        meta_lines.append(f"年份：{paper['year']}")
    if paper.get('journal'):
        journal = paper['journal']
        if len(journal) > 30:
            journal = journal[:27] + '...'
        meta_lines.append(f"期刊：{journal}")
    if paper.get('citations') is not None:
        meta_lines.append(f"引用量：{paper['citations']}")
    if meta_lines:
        fig.text(0.05, 0.05, '\n'.join(meta_lines),
                 ha='left', va='bottom', fontsize=9, color='#606266',
                 bbox=dict(boxstyle='round,pad=0.4', facecolor='#f5f7fa',
                           edgecolor='#dcdfe6', alpha=0.9))

    # 水印（底部居中）
    fig.text(0.5, 0.02,
             'Generated by Paper Analysis Engine | pae.example.com',
             ha='center', fontsize=8, color='grey', alpha=0.7, style='italic')

    # 保存为 PNG
    buf = BytesIO()
    plt.savefig(buf, format='png', dpi=150, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close()
    buf.seek(0)
    return buf.read()


if __name__ == '__main__':
    # 测试用例
    test_paper = {
        'title': 'Attention Is All You Need: Transformer Networks for Natural Language Processing',
        'year': 2017,
        'journal': 'NeurIPS',
        'citations': 100000,
    }
    test_rating = {
        'academic_impact': 95.5,
        'commercial_potential': 88.2,
        'innovation_index': 92.0,
        'reproducibility': 75.0,
        'combo_value': 80.5,
        'overall_score': 87.3,
        'rating_level': 'A',
    }
    img = generate_scorecard(test_paper, test_rating)
    with open('test_scorecard.png', 'wb') as f:
        f.write(img)
    print(f'[OK] 测试评分卡已生成：test_scorecard.png ({len(img)} bytes)')
